version: "3.3"

services:
  backend:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    environment:
      CONFIG_PATH: /app/configs/config.toml
    ports:
      - "8001:8001"
    volumes:
      - ../user_microservice/src:/app/src:ro
      - ../user_microservice/src/infra/postgres/migration/versions:/app/src/infra/postgres/migration/versions:rw

  database:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5400:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.co
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
