"""null

Revision ID: 1140e6a98fed
Revises: 88809ed1b4fd
Create Date: 2025-11-30 18:20:38.993671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1140e6a98fed'
down_revision: Union[str, Sequence[str], None] = '88809ed1b4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='user_microservice_schema')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='user_microservice_schema')
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='user_microservice_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='user_microservice_schema')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='user_microservice_schema')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='user_microservice_schema')
    # ### end Alembic commands ###
