"""size

Revision ID: 945eb1ee550e
Revises: 1140e6a98fed
Create Date: 2025-12-04 18:52:34.006478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945eb1ee550e'
down_revision: Union[str, Sequence[str], None] = '1140e6a98fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baskets', 'size',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='user_microservice_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baskets', 'size',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='user_microservice_schema')
    # ### end Alembic commands ###
