"""size

Revision ID: aee874a3dc4b
Revises: 945eb1ee550e
Create Date: 2025-12-06 19:30:38.319782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee874a3dc4b'
down_revision: Union[str, Sequence[str], None] = '945eb1ee550e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('size', sa.String(), nullable=True), schema='user_microservice_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'size', schema='user_microservice_schema')
    # ### end Alembic commands ###
