"""id_address

Revision ID: 53e70a08e75b
Revises: b87bb27f4377
Create Date: 2025-12-11 20:22:49.325151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e70a08e75b'
down_revision: Union[str, Sequence[str], None] = 'b87bb27f4377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('id_address', sa.UUID(), nullable=False), schema='orders_microservice_schema')
    op.drop_column('orders', 'id_addresses', schema='orders_microservice_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('id_addresses', sa.UUID(), autoincrement=False, nullable=False), schema='orders_microservice_schema')
    op.drop_column('orders', 'id_address', schema='orders_microservice_schema')
    # ### end Alembic commands ###
