"""id_designer

Revision ID: b87bb27f4377
Revises: 6d61794933df
Create Date: 2025-12-11 12:39:23.056925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87bb27f4377'
down_revision: Union[str, Sequence[str], None] = '6d61794933df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_order', sa.UUID(), nullable=False),
    sa.Column('id_status', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='orders_microservice_schema'
    )
    op.create_table('status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='orders_microservice_schema'
    )
    op.add_column('orders', sa.Column('id_status', sa.UUID(), nullable=False), schema='orders_microservice_schema')
    op.add_column('orders', sa.Column('id_designer', sa.UUID(), nullable=False), schema='orders_microservice_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'id_designer', schema='orders_microservice_schema')
    op.drop_column('orders', 'id_status', schema='orders_microservice_schema')
    op.drop_table('status', schema='orders_microservice_schema')
    op.drop_table('order_status', schema='orders_microservice_schema')
    # ### end Alembic commands ###
