name: Build Docker Image on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -f deploy/Dockerfile -t ghcr.io/${{ github.repository_owner }}/user_nicho:pr-${{ github.event.pull_request.number }} deploy/

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/user_nicho:pr-${{ github.event.pull_request.number }}
