name: Build Docker Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deploy/Dockerfile
          push: true
          tags: |
            ghcr.io/lizag000/user_microservice/nicho:latest
            ${{ github.event_name == 'pull_request' && format('ghcr.io/lizag000/user_microservice/nicho:pr-{0}', github.event.number) || format('ghcr.io/lizag000/user_microservice/nicho:{0}', github.sha) }}
